#ifndef FOCSTIM_ERROR_H
#define FOCSTIM_ERROR_H

enum FOCError {
    OUTPUT_OVER_CURRENT,
    MODEL_TIMING_ERROR,
    BOOST_VOLTAGE_NOT_RISING,
    BOOST_UNDER_VOLTAGE,
    BOOST_OVER_VOLTAGE,
    BOARD_OVER_TEMPERATURE,
};

#endif